# Generated by Django 5.2.17 on 2026-09-16 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='codingprogress',
            name='unique_user_coding_problem',
        ),
        migrations.RemoveField(
            model_name='codingproblem',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='codingprogress',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='problem',
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='topic_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='codingprogress',
            name='problem_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='problem_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='problem_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='codingprogress',
            constraint=models.UniqueConstraint(fields=('user', 'problem_id'), name='unique_user_coding_problem'),
        ),
    ]
