# Generated by Django 5.2.17 on 2026-09-16 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='unique_interview_bookmark',
        ),
        migrations.RemoveConstraint(
            model_name='interviewprogress',
            name='unique_user_interview_progress',
        ),
        migrations.RemoveConstraint(
            model_name='useranswer',
            name='unique_user_interview_answer',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='coding_problem',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='interview_question',
        ),
        migrations.RemoveField(
            model_name='interviewprogress',
            name='question',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='coding_problem_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='interview_question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewprogress',
            name='question_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='topic_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'interview_question_id'), name='unique_interview_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='interviewprogress',
            constraint=models.UniqueConstraint(fields=('user', 'question_id'), name='unique_user_interview_progress'),
        ),
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.UniqueConstraint(fields=('user', 'question_id'), name='unique_user_interview_answer'),
        ),
    ]
