# Generated by Django 5.2.17 on 2026-09-08 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_questionprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='questionprogress',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_user_question_progress'),
        ),
    ]
