# Generated by Django 5.2.17 on 2026-09-17 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_lessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lessonprogress',
            name='unique_user_lesson_progress',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='content',
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='content_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('user', 'content_id'), name='unique_user_lesson_progress'),
        ),
    ]
